name: Reproduce bug

on: 
  workflow_dispatch:
  push:




jobs:
  reproduce_bug:
    name: Reproduce bug
    runs-on: ubuntu-latest


    steps:

      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
            enable-cache: false

      - name: Start cassandra container
        run: docker compose up -d

      - name: Wait 10 seconds and run main script with uv
        run: sleep 10 && uv run main.py
        

      
